---
name: Run Go tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'go/**'
      - '.github/workflows/push-go.yaml'

jobs:

  go-build:
    strategy:
      matrix:
        go:
          - '1.18'
          - '1.19'
        os:
          - ubuntu-22.04
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Running unit tests
        run: make test-coverage
        working-directory: go
      - name: Build example app
        run: make build/example
        working-directory: go
