---
name: Run Go tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'go/**'

jobs:

  go-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go:
          - '1.18'
          - '1.19'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Running unit tests
        run: make test-coverage
        working-directory: go
      - name: Build example app
        run: make build/example
        working-directory: go
